# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e43b307bfa40a29682a8ab08cf6d8cb03b5196edec844d70c387f9cb501002c7033f93d2ef15e13b6b16636ebbe8ee725143fd7f19ceeb0404783c09049ab47d

test:
  secret_key_base: 8f0ccab5c960a2ec44e27ad731f880af4f89e0f29eb257cc7e74fca3bb2930fcb0583ee8da1cdf08ddd23cb9783e81301a13c1fa335d37969cbecfba279a2a14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
